bump: imagemagick

diff --git a/scripts/modules/png2ppm b/scripts/modules/png2ppm
--- a/scripts/modules/png2ppm
+++ b/scripts/modules/png2ppm
@@ -1,5 +1,5 @@
 #!/bin/bash
-convert=`which convert` || echo "convert not found"
+convert=`which magick` || echo "magick not found"
 png2ppm() {
   if [ -e "$convert" ] ; then $convert "$2" -resize "$1" -grayscale Rec709luminance -compress none pgm:- > "$3"; return 0; fi;
   throw "Required software is not found
diff --git a/scripts/modules/svg2png b/scripts/modules/svg2png
--- a/scripts/modules/svg2png
+++ b/scripts/modules/svg2png
@@ -1,7 +1,7 @@
 #!/bin/bash
 rsvg=`which rsvg-convert` || echo "rsvg-convert not found"
 qlmanage=`which qlmanage` || echo "qlmanage not found"
-convert=`which convert` || echo "convert not found"
+convert=`which magick` || echo "magick not found"
 inkscape=`which /Applications/Inkscape.app/Contents/MacOS/inkscape` || echo "inkscape not found"
 svg2png() {
   if [ -e "$rsvg" ] ; then $rsvg -w $1 $2 > $3; return 0; fi;
